[build.environment]
  NODE_VERSION = "14"

[build]
  publish = "dist"
  command = "npx playwright install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"
  PLAYWRIGHT_BROWSERS_PATH = "0"

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[[redirects]]
  from = "/2022/vue3-ecosystem/*"
  to = "/2022/vue3-ecosystem/index.html"
  status = 200
